const PRODUCTS = [
  // ===================== PC CABINETS / CASES =====================
  {
    id: "case-lianli-o11",
    cat: "case",
    caseStyle: "panoramic",
    name: "Lian Li O11 Vision Chrome",
    tag: "Panoramic Glass",
    price: 139,
    score: { cpu: 0, gpu: 0, ram: 0, mobo: 0, cooler: 0, case: 98, create: 90 },
    spec: "Seamless 3-Sided Glass · Dual Chamber · E-ATX",
    image: "images/case-lianli-o11.jpg",
  },
  {
    id: "case-corsair-6500x",
    cat: "case",
    caseStyle: "panoramic",
    name: "Corsair 6500X Dual-Chamber",
    tag: "Dual-Chamber",
    price: 199,
    score: { cpu: 0, gpu: 0, ram: 0, mobo: 0, cooler: 0, case: 95, create: 88 },
    spec: "Panoramic Tempered Glass · Reverse Connector Ready",
    image: "images/case-corsair-6500x.jpg",
  },
  {
    id: "case-nzxt-h9",
    cat: "case",
    caseStyle: "panoramic",
    name: "NZXT H9 Flow Panoramic",
    tag: "High Airflow",
    price: 159,
    score: { cpu: 0, gpu: 0, ram: 0, mobo: 0, cooler: 0, case: 94, create: 86 },
    spec: "Uninterrupted Glass · Perforated Top Mesh · ATX",
    image: "images/case-nzxt-h9.jpg",
  },
  {
    id: "case-fractal-north",
    cat: "case",
    caseStyle: "wood",
    name: "Fractal Design North XL",
    tag: "Walnut Wood",
    price: 189,
    score: { cpu: 0, gpu: 0, ram: 0, mobo: 0, cooler: 0, case: 96, create: 92 },
    spec: "Real Walnut Wood Slats · Tinted Glass · Brass Trim",
    image: "images/case-fractal-north.jpg",
  },
  {
    id: "case-thunder-armor",
    cat: "case",
    caseStyle: "armor",
    name: "Thunder Armorbox Panoramic",
    tag: "Heavy Armor",
    price: 99,
    score: { cpu: 0, gpu: 0, ram: 0, mobo: 0, cooler: 0, case: 86, create: 78 },
    spec: "Armor Plating · Honeycomb Mesh · Curved Glass",
    image: "images/case-thunder-armor.jpg",
  },

  // ===================== PROCESSORS (CPU) =====================
  {
    id: "cpu-9800x3d",
    cat: "cpu",
    name: "Ryzen 7 9800X3D",
    tag: "Gaming King",
    price: 479,
    score: { cpu: 96, gpu: 0, ram: 0, mobo: 0, cooler: 0, case: 0, create: 82 },
    spec: "8C / 16T · 5.2 GHz · AM5",
    image: "images/cpu-9800x3d.jpg",
  },
  {
    id: "cpu-9950x3d",
    cat: "cpu",
    name: "Ryzen 9 9950X3D",
    tag: "All-Core Titan",
    price: 699,
    score: { cpu: 99, gpu: 0, ram: 0, mobo: 0, cooler: 0, case: 0, create: 98 },
    spec: "16C / 32T · 5.7 GHz · AM5",
    image: "images/cpu-9950x3d.jpg",
  },
  {
    id: "cpu-285k",
    cat: "cpu",
    name: "Core Ultra 9 285K",
    tag: "Intel Flagship",
    price: 589,
    score: { cpu: 90, gpu: 0, ram: 0, mobo: 0, cooler: 0, case: 0, create: 94 },
    spec: "24C · Arrow Lake · LGA 1851",
    image: "images/cpu-285k.jpg",
  },
  {
    id: "cpu-9600x",
    cat: "cpu",
    name: "Ryzen 5 9600X",
    tag: "AM5 Value",
    price: 249,
    score: { cpu: 78, gpu: 0, ram: 0, mobo: 0, cooler: 0, case: 0, create: 64 },
    spec: "6C / 12T · 5.4 GHz · AM5",
    image: "images/cpu-9600x.jpg",
  },
  // AM4 Processors
  {
    id: "cpu-5800x3d",
    cat: "cpu",
    name: "Ryzen 7 5800X3D",
    tag: "AM4 Legend",
    price: 289,
    score: { cpu: 76, gpu: 0, ram: 0, mobo: 0, cooler: 0, case: 0, create: 62 },
    spec: "8C / 16T · 3D V-Cache · AM4",
    image: "images/cpu-5800x3d.jpg",
  },
  {
    id: "cpu-5700x",
    cat: "cpu",
    name: "Ryzen 7 5700X",
    tag: "AM4 Sweetspot",
    price: 169,
    score: { cpu: 66, gpu: 0, ram: 0, mobo: 0, cooler: 0, case: 0, create: 58 },
    spec: "8C / 16T · 4.6 GHz · AM4",
    image: "images/cpu-5700x.jpg",
  },
  {
    id: "cpu-5600x",
    cat: "cpu",
    name: "Ryzen 5 5600X",
    tag: "Budget Champion",
    price: 129,
    score: { cpu: 58, gpu: 0, ram: 0, mobo: 0, cooler: 0, case: 0, create: 48 },
    spec: "6C / 12T · 4.6 GHz · AM4",
    image: "images/cpu-5600x.jpg",
  },

  // ===================== GRAPHICS CARDS (GPU) =====================
  // NVIDIA RTX 50 Series
  {
    id: "gpu-5090",
    cat: "gpu",
    name: "GeForce RTX 5090",
    tag: "Market Peak",
    price: 1999,
    score: { cpu: 0, gpu: 100, ram: 0, mobo: 0, cooler: 0, case: 0, create: 100 },
    spec: "32 GB GDDR7 · 4K Ultra",
    image: "images/gpu-5090.jpg",
  },
  {
    id: "gpu-5080",
    cat: "gpu",
    name: "GeForce RTX 5080",
    tag: "1440p–4K King",
    price: 999,
    score: { cpu: 0, gpu: 86, ram: 0, mobo: 0, cooler: 0, create: 88 },
    spec: "16 GB GDDR7 · DLSS 4",
    image: "images/gpu-5080.jpg",
  },
  {
    id: "gpu-5070ti",
    cat: "gpu",
    name: "GeForce RTX 5070 Ti",
    tag: "High FPS",
    price: 749,
    score: { cpu: 0, gpu: 76, ram: 0, mobo: 0, cooler: 0, case: 0, create: 76 },
    spec: "16 GB GDDR7 · 1440p",
    image: "images/gpu-5070ti.jpg",
  },
  // NVIDIA RTX 40 Series
  {
    id: "gpu-4090",
    cat: "gpu",
    name: "GeForce RTX 4090",
    tag: "Ada Titan",
    price: 1649,
    score: { cpu: 0, gpu: 94, ram: 0, mobo: 0, cooler: 0, case: 0, create: 95 },
    spec: "24 GB GDDR6X · DLSS 3.5",
    image: "images/gpu-4090.jpg",
  },
  {
    id: "gpu-4080s",
    cat: "gpu",
    name: "GeForce RTX 4080 Super",
    tag: "4K Enthusiast",
    price: 899,
    score: { cpu: 0, gpu: 82, ram: 0, mobo: 0, cooler: 0, case: 0, create: 82 },
    spec: "16 GB GDDR6X · 4K",
    image: "images/gpu-4080s.jpg",
  },
  {
    id: "gpu-4070tis",
    cat: "gpu",
    name: "GeForce RTX 4070 Ti Super",
    tag: "16GB Sweetspot",
    price: 699,
    score: { cpu: 0, gpu: 72, ram: 0, mobo: 0, cooler: 0, case: 0, create: 72 },
    spec: "16 GB GDDR6X · 1440p Ultra",
    image: "images/gpu-4070tis.jpg",
  },
  // NVIDIA RTX 30 Series
  {
    id: "gpu-3080",
    cat: "gpu",
    name: "GeForce RTX 3080",
    tag: "Ampere Power",
    price: 499,
    score: { cpu: 0, gpu: 64, ram: 0, mobo: 0, cooler: 0, case: 0, create: 62 },
    spec: "10 GB GDDR6X · 1440p High",
    image: "images/gpu-3080.jpg",
  },
  {
    id: "gpu-3060ti",
    cat: "gpu",
    name: "GeForce RTX 3060 Ti",
    tag: "Value 1080p",
    price: 299,
    score: { cpu: 0, gpu: 46, ram: 0, mobo: 0, cooler: 0, case: 0, create: 42 },
    spec: "8 GB GDDR6 · 1080p Max",
    image: "images/gpu-3060ti.jpg",
  },
  // NVIDIA RTX 20 Series
  {
    id: "gpu-2080ti",
    cat: "gpu",
    name: "GeForce RTX 2080 Ti",
    tag: "Turing Icon",
    price: 349,
    score: { cpu: 0, gpu: 50, ram: 0, mobo: 0, cooler: 0, case: 0, create: 48 },
    spec: "11 GB GDDR6 · Ray Tracing",
    image: "images/gpu-2080ti.jpg",
  },
  // AMD Radeon RX 7000 Series
  {
    id: "gpu-7900xtx",
    cat: "gpu",
    name: "Radeon RX 7900 XTX",
    tag: "RDNA 3 Flagship",
    price: 949,
    score: { cpu: 0, gpu: 88, ram: 0, mobo: 0, cooler: 0, case: 0, create: 84 },
    spec: "24 GB GDDR6 · 4K Ultra · DisplayPort 2.1",
    image: "images/gpu-7900xtx.jpg",
  },
  {
    id: "gpu-7900xt",
    cat: "gpu",
    name: "Radeon RX 7900 XT",
    tag: "RDNA 3 High-End",
    price: 699,
    score: { cpu: 0, gpu: 78, ram: 0, mobo: 0, cooler: 0, case: 0, create: 75 },
    spec: "20 GB GDDR6 · 1440p-4K Gaming",
    image: "images/gpu-7900xt.jpg",
  },
  {
    id: "gpu-7800xt",
    cat: "gpu",
    name: "Radeon RX 7800 XT",
    tag: "1440p Sweetspot",
    price: 499,
    score: { cpu: 0, gpu: 68, ram: 0, mobo: 0, cooler: 0, case: 0, create: 65 },
    spec: "16 GB GDDR6 · 1440p Max FPS",
    image: "images/gpu-7800xt.jpg",
  },
  {
    id: "gpu-7700xt",
    cat: "gpu",
    name: "Radeon RX 7700 XT",
    tag: "RDNA 3 Value",
    price: 399,
    score: { cpu: 0, gpu: 58, ram: 0, mobo: 0, cooler: 0, case: 0, create: 54 },
    spec: "12 GB GDDR6 · High Refresh 1440p",
    image: "images/gpu-7700xt.jpg",
  },
  // AMD Radeon RX 6000 Series
  {
    id: "gpu-6950xt",
    cat: "gpu",
    name: "Radeon RX 6950 XT",
    tag: "RDNA 2 King",
    price: 549,
    score: { cpu: 0, gpu: 70, ram: 0, mobo: 0, cooler: 0, case: 0, create: 66 },
    spec: "16 GB GDDR6 · 4K Gaming Monster",
    image: "images/gpu-6950xt.jpg",
  },
  {
    id: "gpu-6800xt",
    cat: "gpu",
    name: "Radeon RX 6800 XT",
    tag: "16GB Benchmark",
    price: 429,
    score: { cpu: 0, gpu: 62, ram: 0, mobo: 0, cooler: 0, case: 0, create: 58 },
    spec: "16 GB GDDR6 · 1440p Heavyweight",
    image: "images/gpu-6800xt.jpg",
  },
  {
    id: "gpu-6700xt",
    cat: "gpu",
    name: "Radeon RX 6700 XT",
    tag: "Budget 1440p",
    price: 319,
    score: { cpu: 0, gpu: 50, ram: 0, mobo: 0, cooler: 0, case: 0, create: 46 },
    spec: "12 GB GDDR6 · High FPS 1080p/1440p",
    image: "images/gpu-6700xt.jpg",
  },
  {
    id: "gpu-6600",
    cat: "gpu",
    name: "Radeon RX 6600",
    tag: "Budget Esports",
    price: 199,
    score: { cpu: 0, gpu: 40, ram: 0, mobo: 0, cooler: 0, case: 0, create: 36 },
    spec: "8 GB GDDR6 · 1080p Esports Standard",
    image: "images/gpu-6600.jpg",
  },
  // Next-Gen Radeon
  {
    id: "gpu-9070xt",
    cat: "gpu",
    name: "Radeon RX 9070 XT",
    tag: "Raster Punch",
    price: 599,
    score: { cpu: 0, gpu: 70, ram: 0, mobo: 0, cooler: 0, case: 0, create: 68 },
    spec: "16 GB · RDNA 4 · 1440p",
    image: "images/gpu-9070xt.jpg",
  },

  // ===================== MEMORY (RAM - KINGSTON, CORSAIR, SAMSUNG, G.SKILL) =====================
  // Corsair
  {
    id: "ram-corsair-titanium",
    cat: "ram",
    name: "Corsair Dominator Titanium 32 GB DDR5",
    tag: "Luxury ARGB",
    price: 179,
    score: { cpu: 0, gpu: 0, ram: 92, mobo: 0, cooler: 0, case: 0, create: 88 },
    spec: "2×16 GB · 6600MHz CL32 · White/Dark",
    image: "images/ram-corsair-titanium.jpg",
  },
  {
    id: "ram-corsair-vengeance-d5",
    cat: "ram",
    name: "Corsair Vengeance RGB 32 GB DDR5",
    tag: "Corsair iCUE",
    price: 129,
    score: { cpu: 0, gpu: 0, ram: 84, mobo: 0, cooler: 0, case: 0, create: 78 },
    spec: "2×16 GB · 6000MHz CL30 · Ten-Zone RGB",
    image: "images/ram-corsair-vengeance.jpg",
  },
  {
    id: "ram-corsair-lpx-d4",
    cat: "ram",
    name: "Corsair Vengeance LPX 16 GB DDR4",
    tag: "Low Profile",
    price: 49,
    score: { cpu: 0, gpu: 0, ram: 52, mobo: 0, cooler: 0, case: 0, create: 48 },
    spec: "2×8 GB · 3600MHz CL18 · DDR4",
    image: "images/ram-corsair-lpx.jpg",
  },
  // Kingston
  {
    id: "ram-kingston-beast-d5",
    cat: "ram",
    name: "Kingston FURY Beast 32 GB DDR5 RGB",
    tag: "Infrared Sync",
    price: 124,
    score: { cpu: 0, gpu: 0, ram: 82, mobo: 0, cooler: 0, case: 0, create: 76 },
    spec: "2×16 GB · 6000MHz CL30 · Dynamic RGB",
    image: "images/ram-kingston-beast.jpg",
  },
  {
    id: "ram-kingston-renegade-d4",
    cat: "ram",
    name: "Kingston FURY Renegade 16 GB DDR4",
    tag: "Renegade RGB",
    price: 55,
    score: { cpu: 0, gpu: 0, ram: 56, mobo: 0, cooler: 0, case: 0, create: 52 },
    spec: "2×8 GB · 3600MHz CL16 · Low Latency",
    image: "images/ram-kingston-renegade.jpg",
  },
  // Samsung
  {
    id: "ram-samsung-d5-32",
    cat: "ram",
    name: "Samsung Performance 32 GB DDR5",
    tag: "Pure Silicon",
    price: 109,
    score: { cpu: 0, gpu: 0, ram: 78, mobo: 0, cooler: 0, case: 0, create: 74 },
    spec: "2×16 GB · 5600MHz CL36 · High Stability",
    image: "images/ram-samsung-d5.png",
  },
  // G.Skill & High-Capacity
  {
    id: "ram-32-6000",
    cat: "ram",
    name: "G.Skill Trident Z5 RGB 32 GB",
    tag: "Gaming Standard",
    price: 119,
    score: { cpu: 0, gpu: 0, ram: 80, mobo: 0, cooler: 0, case: 0, create: 76 },
    spec: "2×16 GB · 6000MHz CL30 · EXPO / XMP",
    image: "images/ram-32-6000.jpg",
  },
  {
    id: "ram-64-6400",
    cat: "ram",
    name: "G.Skill Trident Z5 64 GB DDR5",
    tag: "Creator Stack",
    price: 229,
    score: { cpu: 0, gpu: 0, ram: 92, mobo: 0, cooler: 0, case: 0, create: 90 },
    spec: "2×32 GB · 6400MHz CL32 · Ultra Fast",
    image: "images/ram-64-6400.jpg",
  },
  {
    id: "ram-96-5600",
    cat: "ram",
    name: "Trident Z5 96 GB High-Capacity",
    tag: "Workstation Titan",
    price: 319,
    score: { cpu: 0, gpu: 0, ram: 96, mobo: 0, cooler: 0, case: 0, create: 95 },
    spec: "2×48 GB · Non-Binary High Density",
    image: "images/ram-96-5600.jpg",
  },

  // ===================== COOLERS (LIQUID AIO & NORMAL AIR COOLERS) =====================
  // Liquid Coolers (AIO)
  {
    id: "cooler-kraken-360",
    cat: "cooler",
    coolerType: "liquid",
    name: "NZXT Kraken Elite 360 RGB",
    tag: "AIO LCD Titan",
    price: 279,
    score: { cpu: 0, gpu: 0, ram: 0, mobo: 0, cooler: 96, case: 0, create: 92 },
    spec: "360mm Radiator · 2.36\" LCD · F120 RGB Core Fans",
    image: "images/cooler-kraken-360.jpg",
  },
  {
    id: "cooler-icue-titan-360",
    cat: "cooler",
    coolerType: "liquid",
    name: "Corsair iCUE LINK Titan 360 RX",
    tag: "Magnetic ARGB",
    price: 259,
    score: { cpu: 0, gpu: 0, ram: 0, mobo: 0, cooler: 94, case: 0, create: 90 },
    spec: "360mm Radiator · Capellix RGB · FlowDrive Pump",
    image: "images/cooler-icue-titan-360.jpg",
  },
  {
    id: "cooler-galahad-360",
    cat: "cooler",
    coolerType: "liquid",
    name: "Lian Li Galahad II LCD 360 ARGB",
    tag: "Infinity Mirror",
    price: 249,
    score: { cpu: 0, gpu: 0, ram: 0, mobo: 0, cooler: 93, case: 0, create: 88 },
    spec: "360mm Radiator · 2.88\" IPS Screen · ARGB Daisy-Chain",
    image: "images/cooler-galahad-360.jpg",
  },
  {
    id: "cooler-ryujin-360",
    cat: "cooler",
    coolerType: "liquid",
    name: "ASUS ROG Ryujin III 360 ARGB",
    tag: "Flagship AIO",
    price: 349,
    score: { cpu: 0, gpu: 0, ram: 0, mobo: 0, cooler: 98, case: 0, create: 95 },
    spec: "3.5\" Full Color LCD · Asetek 8th Gen · ARGB Magnetic Fans",
    image: "images/cooler-ryujin-360.jpg",
  },
  // Normal Air Coolers
  {
    id: "cooler-ak620-digital",
    cat: "cooler",
    coolerType: "air",
    name: "DeepCool AK620 Digital ARGB",
    tag: "Digital Air",
    price: 89,
    score: { cpu: 0, gpu: 0, ram: 0, mobo: 0, cooler: 82, case: 0, create: 78 },
    spec: "Dual-Tower · Real-Time Digital Display · ARGB Accents",
    image: "images/cooler-ak620-digital.jpg",
  },
  {
    id: "cooler-peerless-120",
    cat: "cooler",
    coolerType: "air",
    name: "Thermalright Peerless Assassin 120 SE",
    tag: "Value Champion",
    price: 45,
    score: { cpu: 0, gpu: 0, ram: 0, mobo: 0, cooler: 79, case: 0, create: 74 },
    spec: "Dual-Tower · 6 Heatpipes · Dual 120mm ARGB Fans",
    image: "images/cooler-peerless-120.png",
  },
  {
    id: "cooler-nh-d15",
    cat: "cooler",
    coolerType: "air",
    name: "Noctua NH-D15 chromax.black",
    tag: "Air Benchmark",
    price: 119,
    score: { cpu: 0, gpu: 0, ram: 0, mobo: 0, cooler: 89, case: 0, create: 84 },
    spec: "Dual-Tower · 6 Heatpipes · Dual NF-A15 PWM Fans",
    image: "images/cooler-nh-d15.jpg",
  },
  {
    id: "cooler-darkrock-pro5",
    cat: "cooler",
    coolerType: "air",
    name: "be quiet! Dark Rock Pro 5",
    tag: "Silent Pro",
    price: 99,
    score: { cpu: 0, gpu: 0, ram: 0, mobo: 0, cooler: 86, case: 0, create: 82 },
    spec: "7 Heatpipes · 270W TDP · Silent Wings PWM Fans",
    image: "images/cooler-darkrock-pro5.jpg",
  },

  // ===================== MOTHERBOARDS =====================
  // AM4 & DDR4 Motherboards
  {
    id: "mobo-b550",
    cat: "mobo",
    name: "B550 Steel Gaming",
    tag: "AM4 DDR4",
    price: 139,
    score: { cpu: 0, gpu: 0, ram: 0, mobo: 72, cooler: 0, case: 0, create: 56 },
    spec: "AM4 · PCIe 4.0 · Wi-Fi 6 · DDR4",
    image: "images/mobo-b550.png",
  },
  {
    id: "mobo-x570s",
    cat: "mobo",
    name: "X570S Dark Hero",
    tag: "AM4 Flagship",
    price: 269,
    score: { cpu: 0, gpu: 0, ram: 0, mobo: 86, cooler: 0, case: 0, create: 74 },
    spec: "AM4 · Passive VRM · Dual M.2 DDR4",
    image: "images/mobo-x570s.jpg",
  },
  {
    id: "mobo-b760d4",
    cat: "mobo",
    name: "B760 Storm DDR4",
    tag: "LGA 1700 DDR4",
    price: 149,
    score: { cpu: 0, gpu: 0, ram: 0, mobo: 74, cooler: 0, case: 0, create: 60 },
    spec: "Intel 12-14th Gen · PCIe 4.0 · DDR4",
    image: "images/mobo-b760d4.jpg",
  },
  // AM5 & Next-Gen Intel Motherboards
  {
    id: "mobo-x870e",
    cat: "mobo",
    name: "X870E Darkline",
    tag: "AM5 Flagship",
    price: 429,
    score: { cpu: 0, gpu: 0, ram: 0, mobo: 98, cooler: 0, case: 0, create: 82 },
    spec: "AM5 · PCIe 5.0 · Dual USB4 · DDR5",
    image: "images/mobo-x870e.jpg",
  },
  {
    id: "mobo-b850",
    cat: "mobo",
    name: "B850 Shadow",
    tag: "AM5 Sweetspot",
    price: 189,
    score: { cpu: 0, gpu: 0, ram: 0, mobo: 78, cooler: 0, case: 0, create: 64 },
    spec: "AM5 · PCIe 5.0 M.2 · Wi-Fi 7 · DDR5",
    image: "images/mobo-b850.jpg",
  },
  {
    id: "mobo-z890",
    cat: "mobo",
    name: "Z890 Monolith",
    tag: "LGA 1851 Flagship",
    price: 399,
    score: { cpu: 0, gpu: 0, ram: 0, mobo: 94, cooler: 0, case: 0, create: 80 },
    spec: "Core Ultra · Thunderbolt 4 · DDR5",
    image: "images/mobo-z890.jpg",
  },
];

const CAT_LABEL = {
  case: "Case / Cabinet",
  cpu: "CPU",
  gpu: "GPU",
  ram: "RAM",
  cooler: "Cooling",
  mobo: "Motherboard",
};

const FEATURED_BUILDS = [
  {
    id: "build-titan",
    name: "Titan 5090 Godtier",
    badge: "Flagship 4K Ultra",
    desc: "Custom hardline liquid cooling loop with GeForce RTX 5090 and Ryzen 9 9950X3D in Lian Li O11 Vision.",
    price: 4899,
    image: "images/build-titan.jpg",
    specs: ["Lian Li O11 Vision", "RTX 5090 32GB", "Ryzen 9 9950X3D", "Kraken Elite 360", "64GB DDR5-6400"],
    perf: 99,
  },
  {
    id: "build-apex",
    name: "Apex Esports Striker",
    badge: "Fastest Gaming FPS",
    desc: "Built around Ryzen 7 9800X3D and RTX 5080 with dual-chamber panoramic glass in Corsair 6500X.",
    price: 3249,
    image: "images/build-apex.jpg",
    specs: ["Corsair 6500X", "RTX 5080 16GB", "Ryzen 7 9800X3D", "Galahad II 360", "32GB DDR5-6000"],
    perf: 92,
  },
  {
    id: "build-obsidian",
    name: "Obsidian Creator Studio",
    badge: "24-Core Workstation",
    desc: "Core Ultra 9 285K paired with RTX 5070 Ti, AK620 Digital Air, and 96GB RAM in Fractal North XL.",
    price: 2899,
    image: "images/build-obsidian.jpg",
    specs: ["Fractal North XL", "RTX 5070 Ti 16GB", "Core Ultra 9 285K", "AK620 Digital", "96GB DDR5-5600"],
    perf: 88,
  },
];

// Official Brands Sold by PC Forge for the Sliding Marquee
const BRAND_SPONSORS = [
  { name: "LIAN LI", tier: "O11 Panoramic Case & Galahad AIO", icon: "💎 LIAN LI" },
  { name: "CORSAIR", tier: "6500X Cases, Dominator RAM & iCUE", icon: "⛵ CORSAIR" },
  { name: "NZXT", tier: "H9 Flow & Kraken LCD Cooling", icon: "🟣 NZXT" },
  { name: "FRACTAL DESIGN", tier: "North XL Wood & Torrent Chassis", icon: "🌲 FRACTAL DESIGN" },
  { name: "THUNDER", tier: "Armorbox High-Airflow Chassis", icon: "⚡ THUNDER" },
  { name: "NVIDIA", tier: "GeForce RTX Flagship Partner", icon: "⚡ NVIDIA" },
  { name: "AMD", tier: "Ryzen 9000 & Radeon RX 7000/6000", icon: "🔴 AMD" },
  { name: "INTEL", tier: "Core Ultra Flagship Architect", icon: "🔷 INTEL" },
  { name: "ASUS ROG", tier: "Republic of Gamers Authorized", icon: "🛡️ ASUS ROG" },
  { name: "MSI", tier: "True Gaming Component Partner", icon: "🐉 MSI GAMING" },
  { name: "KINGSTON FURY", tier: "Beast & Renegade Gaming RAM", icon: "🔥 KINGSTON FURY" },
  { name: "SAMSUNG", tier: "High-Performance DDR5 & 990 Pro", icon: "💾 SAMSUNG" },
  { name: "G.SKILL", tier: "Trident Z Extreme Overclocking", icon: "⚡ G.SKILL" },
  { name: "NOCTUA", tier: "Legendary Stealth Silent Air Cooling", icon: "🦉 NOCTUA" },
  { name: "DEEPCOOL", tier: "Digital Air & ARGB Thermal Systems", icon: "❄️ DEEPCOOL" },
];
